Opencart 4 Support
razorpay/razorpay-opencart pull request #127
Opened 2023-09-13 05:30 UTC by nikhilsharma1100

## Note :- Please follow the below points while attaching test cases document link below:
   ### - If label `Tested` is added then test cases document URL is mandatory.
   ### - Link added should be a valid URL and accessible throughout the org.
   ### - If the branch name contains hotfix / revert by default the BVT workflow check will pass.

| Test Case Document URL                        |
|-----------------------------------------------|
| Please paste test case document link here.... |

2023-09-20 06:34 UTC, nikhilsharma1100 commented on admin/view/template/payment/razorpay.twig
> +<div id="content">
@sofiya02 This view file is for admin save settings page. In opencart 3 I don't see a Razorpay logo on admin save settings page. Where is the logo supposed to be?

2023-09-20 07:41 UTC, nikhilsharma1100 commented on admin/view/template/payment/razorpay.twig
> +				{{ text_edit }}
Updated

2023-09-20 07:52 UTC, nikhilsharma1100 commented on catalog/controller/payment/razorpay.php
> +                if ($this->cart->hasRecurringProducts() > 1)
@sofiya02 As discussed in meeting earlier, we are including the subscriptions code as long it doesn't interfere with the checkout flow. We can spend time on this later when checkout is released for Opencart 4.

2023-09-20 07:54 UTC, nikhilsharma1100 commented on admin/controller/payment/razorpay.php
> +    {
@sofiya02 tested this fn. It works fine.

2023-09-20 08:04 UTC, nikhilsharma1100 commented on catalog/controller/payment/razorpay.php
> +        $this->log->write('In OP logs');
Updated, please check.

2023-09-20 08:04 UTC, nikhilsharma1100 commented on catalog/controller/payment/razorpay.php
> +    private $version = '5.1.0'; //change this
Updated to 6.0.0. Is it fine?

2023-09-20 09:12 UTC, nikhilsharma1100 commented on catalog/controller/payment/razorpay.php
> +            header('Status: 409 Webhook conflicts due to early execution.', true, self::HTTP_CONFLICT_STATUS);
Have identified the issue. Will be updating it

2023-09-20 09:24 UTC, nikhilsharma1100 commented on catalog/controller/payment/razorpay.php
> +            'amount' => $this->currency->format($order['total'], $order['currency_code'], $order['currency_value'], false) * 100,
Fixed

2023-09-20 10:45 UTC, nikhilsharma1100 commented on admin/view/template/payment/razorpay.twig
> +								{% if error_key_id %}
Added validations on client and server side for empty key and invalid key respectively

2023-09-20 10:47 UTC, nikhilsharma1100 commented on install.json
> +  "author": "OpenCart Ltd",
Updated, please check

2023-09-20 10:51 UTC, nikhilsharma1100 commented on admin/controller/payment/razorpay.php
> +    {
okay, I have moved this fn call inside index fn. Found the issue, will update it

2023-09-21 09:41 UTC, nikhilsharma1100 commented on admin/controller/payment/razorpay.php
> +			{
Added check [here](https://github.com/razorpay/razorpay-opencart/pull/127/commits/da4b809be36cfc4f2d8eccc08bf2c0f75d7a67a8)

2023-09-21 09:42 UTC, nikhilsharma1100 commented on admin/view/template/payment/razorpay.twig
> +<div id="content">
Trying to find how I can write the path correctly from View/Template file

2023-09-21 09:43 UTC, nikhilsharma1100 commented on admin/view/template/payment/razorpay.twig
> +								{% if error_key_id %}
[here](https://github.com/razorpay/razorpay-opencart/pull/127/commits/da4b809be36cfc4f2d8eccc08bf2c0f75d7a67a8)

2023-09-27 07:35 UTC, sofiya02 requested changes

2023-09-27 07:35 UTC, sofiya02 commented on admin/view/template/payment/razorpay.twig
> +<div id="content">
is this fixed

2023-09-27 07:35 UTC, sofiya02 commented on catalog/controller/payment/razorpay.php
> +									$this->config->get('payment_razorpay_webhook_updated_at') : null);
php indentation

2023-09-28 07:07 UTC, nikhilsharma1100 commented on catalog/controller/payment/razorpay.php
> +									$this->config->get('payment_razorpay_webhook_updated_at') : null);
updated

2023-09-28 11:07 UTC, nikhilsharma1100 commented on README.md
> +- The `master` branch holds the plugin for OpenCart 3
master will be the branch with latest code

2023-09-28 11:08 UTC, nikhilsharma1100 commented on README.md
> +- The `master` branch holds the plugin for OpenCart 3
Have branched out master into opencartv3-5.1.1

2023-09-28 12:02 UTC, nikhilsharma1100 commented on admin/view/template/payment/razorpay.twig
> +<div id="content">
yes

2023-09-28 12:48 UTC, sofiya02 approved these changes
LGTM

2023-09-28 12:52 UTC, merged